apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backoffice-ingress
  namespace: backoffice-stg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io.ingress.class: "nginx"
spec:
  rules:
    - host: backoffice-api-dev-posicube.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backoffice-backend-svc
                port:
                  number: 8081
    - host: backoffice-web-dev-posicube.com
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: backoffice-front-svc
                  port:
                    number: 80
